# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   twig.markdown:
      class: Lablog\Markdown\Twig\MarkdownLoader
      tags:
        -  { name: twig.extension }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
